name: ci

on: push

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: check builder specs
        run: |
          lscpu
          free -h
          df -h

      - name: git clone
        run: |
          git config --global credential.helper 'cache --timeout=30000'
          git clone https://oauth2:${{ secrets.GITLAB_READ_TOKEN }}@gitlab.com/bookish-disco/sitar.git

      - name: run
        shell: bash
        run: |
          cd sitar
          git checkout ci
          git --no-pager log --decorate=short --pretty=oneline -n5
          bash scripts/run_in_docker.sh


